name = "wh-sites"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "4c559b9dff9fae56803b9c275b518597"

# KV — read live client HTML
[[kv_namespaces]]
binding = "SITES"
id = "b63e5b885ead4c02a9e184dd6477e711"
