name = "wh-launch"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "4c559b9dff9fae56803b9c275b518597"

[vars]
REGISTERDOMAIN_EMAIL = "loc10@live.co.za"
REGISTERDOMAIN_API_KEY = "FhFq5iDgm1GeL1S1aE2eh132PmTpTAzG"
PAYFAST_MERCHANT_ID = "13581217"
CF_ZONE_ID = "e6b58b08eb80ea03a46d010455f6b25d"
CF_ACCOUNT_ID = "4c559b9dff9fae56803b9c275b518597"
TEST_MODE = "false"
WORKER_URL_LAUNCH = "https://wh-launch.pierreduplessis6912.workers.dev"
WORKER_URL_PATCH = "https://wh-patch.pierreduplessis6912.workers.dev"
WORKER_URL_BUILD = "https://wh-build.pierreduplessis6912.workers.dev"

[[routes]]
pattern = "preview.websitehub.co.za/go-live-link"
zone_name = "websitehub.co.za"

[[routes]]
pattern = "preview.websitehub.co.za/activate-free"
zone_name = "websitehub.co.za"

[[routes]]
pattern = "preview.websitehub.co.za/internal-golive"
zone_name = "websitehub.co.za"

[[routes]]
pattern = "preview.websitehub.co.za/google-auth"
zone_name = "websitehub.co.za"

[[kv_namespaces]]
binding = "SITES"
id = "b63e5b885ead4c02a9e184dd6477e711"

[[d1_databases]]
binding = "DB"
database_name = "website-hub-db"
database_id = "9c422081-af06-4c1b-b59e-f40e0d08fefa"
migrations_dir = "../migrations"
