name = "wh-patch"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "4c559b9dff9fae56803b9c275b518597"

[vars]
RESEND_API_KEY = ""
TEST_MODE = "false"
WORKER_URL_BUILD = "https://wh-build.pierreduplessis6912.workers.dev"

[[routes]]
pattern = "preview.websitehub.co.za/manage-panel"
zone_name = "websitehub.co.za"

[[routes]]
pattern = "preview.websitehub.co.za/patch-preview"
zone_name = "websitehub.co.za"

[[routes]]
pattern = "preview.websitehub.co.za/upload-assets"
zone_name = "websitehub.co.za"

[[routes]]
pattern = "preview.websitehub.co.za/submit-revision"
zone_name = "websitehub.co.za"

[[kv_namespaces]]
binding = "SITES"
id = "b63e5b885ead4c02a9e184dd6477e711"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "wh-assets"

[[d1_databases]]
binding = "DB"
database_name = "website-hub-db"
database_id = "9c422081-af06-4c1b-b59e-f40e0d08fefa"
migrations_dir = "../migrations"

send_email = [{binding = "EMAIL", destination_address = "updates@websitehub.co.za"}]
